// src/components/TipCard.tsx
import type { Component } from 'solid-js';
import type { Tip } from '../lib/search';

interface Props {
    tip: Tip;
}

const TipCard: Component<Props> = (props) => {
    return (
        <div class="bg-gray-800 border border-gray-700 rounded-lg p-4 hover:border-gray-500 transition-colors shadow-sm">
            <div class="flex justify-between items-start mb-2">
                <h3 class="text-lg font-bold text-orange-400">{props.tip.title}</h3>
                <span class="text-xs text-gray-500 bg-gray-900 px-2 py-1 rounded">v{props.tip.patch_created}</span>
            </div>

            <p class="text-gray-300 mb-4 text-sm leading-relaxed">{props.tip.content}</p>

            <div class="flex flex-wrap gap-2 mb-3">
                {props.tip.tags.map((tag) => (
                    <span class="text-xs bg-gray-700 text-gray-300 px-2 py-0.5 rounded-full">
                        #{tag}
                    </span>
                ))}
            </div>

            <div class="flex justify-between items-center text-xs text-gray-500 border-t border-gray-700 pt-2 mt-2">
                <span>By {props.tip.author}</span>
                <div class="flex items-center gap-1">
                    <span>▲ {props.tip.vote_count}</span>
                </div>
            </div>
        </div>
    );
};

export default TipCard;

// app/components/TipCard.vue
<script setup lang="ts">
const props = defineProps<{
  tip: any
}>()

const isOpen = ref(false)

const statusColor = computed(() => {
  switch (props.tip.status) {
    case 'verified': return 'success'
    case 'legacy': return 'warning'
    case 'dead': return 'error'
    default: return 'neutral'
  }
})
</script>

<template>
  <UCard class="h-full flex flex-col cursor-pointer hover:ring-2 hover:ring-primary-500 transition-all" @click="isOpen = true">
    <template #header>
      <div class="flex justify-between items-start gap-2">
        <h3 class="text-lg font-bold line-clamp-2">{{ tip.title }}</h3>
        <UBadge :color="statusColor" variant="subtle" size="xs">{{ tip.status }}</UBadge>
      </div>
    </template>

    <p class="text-gray-500 dark:text-gray-400 text-sm line-clamp-3 mb-4">
      {{ tip.description }}
    </p>

    <template #footer>
      <div class="flex flex-wrap gap-1">
        <UBadge v-for="tag in tip.tags" :key="tag" color="neutral" variant="soft" size="xs">
          {{ tag }}
        </UBadge>
      </div>
      <div class="mt-2 text-xs text-gray-400">
        By {{ tip.author }} • Patch {{ tip.last_verified_patch }}
      </div>
    </template>

    <UModal v-model="isOpen">
      <UCard>
        <template #header>
          <div class="flex justify-between items-center">
            <h2 class="text-xl font-bold">{{ tip.title }}</h2>
            <UButton color="neutral" variant="ghost" icon="i-heroicons-x-mark-20-solid" @click="isOpen = false" />
          </div>
        </template>

        <div class="prose dark:prose-invert max-w-none">
          <ContentRenderer :value="tip" />
        </div>

        <template #footer>
          <div class="flex flex-wrap gap-2">
            <UBadge v-for="tag in tip.tags" :key="tag" color="neutral" variant="soft">
              {{ tag }}
            </UBadge>
          </div>
        </template>
      </UCard>
    </UModal>
  </UCard>
</template>
